In [1]:
!pip install numpy

In [3]:
import numpy as np

In [5]:
arr1 = np.array([10,20,30,40,50])
print(arr1)
print(arr1.shape)

[10 20 30 40 50]
(5,)


In [6]:
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [8]:
arr3 =np.array([
    [[1,2],[3,4]],
    [[5,6], [7,8]]
])
print(arr3)
print(arr3.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [10]:
a= np.array([1,2,3])
print(a+10)

[11 12 13]


In [11]:
import pandas as pd

data = {
    "State": ["Karnataka","Tamil Nadu","Kerala","Delhi","Maharashtra"],
    "Population":[67562686,72147030,35699443,16787941,124904071],
    "Area":[191791,130058,38863,1484,307713]
}

df = pd.DataFrame(data)

df.to_csv("india_population.csv", index=False)

print("CSV Created Successfully")

CSV Created Successfully


In [13]:
df = pd.read_csv("india_population.csv")
print(df)

         State  Population    Area
0    Karnataka    67562686  191791
1   Tamil Nadu    72147030  130058
2       Kerala    35699443   38863
3        Delhi    16787941    1484
4  Maharashtra   124904071  307713


In [14]:
population = df["Population"].to_numpy()
print(population)

[ 67562686  72147030  35699443  16787941 124904071]


In [15]:
mean= np.mean(population)
print(mean)

63420234.2
